server:
  port: 8888

spring:
  application:
    name: config-server
#spring.cloud.config≈‰÷√
  cloud:
    config:
      server:
        label: master
        git:
          uri: https://github.com/forezp/SpringcloudConfig/
          searchPaths: respo
          username:
          password:

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/







